-- phpMyAdmin SQL Dump
-- version 3.4.2
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Feb 17, 2012 at 09:28 PM
-- Server version: 5.5.19
-- PHP Version: 5.3.10

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `avi_smarty_test`
--

-- --------------------------------------------------------

--
-- Table structure for table `tbl_article`
--

CREATE TABLE IF NOT EXISTS `tbl_article` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(128) NOT NULL,
  `author_id` int(11) NOT NULL,
  `article_text` text NOT NULL,
  `created_on` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=51 ;

--
-- Dumping data for table `tbl_article`
--

INSERT INTO `tbl_article` (`id`, `title`, `author_id`, `article_text`, `created_on`) VALUES
(1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ornare tortor tortor. Nam eros velit, venenatis vitae sodales nec, tempor vel leo. Nullam hendrerit pharetra ligula ut dignissim. Suspendisse ornare nisl non felis ornare id consectetur sem vulputate. Morbi vehicula dapibus porta. Sed sagittis felis at libero elementum porttitor. Aenean accumsan congue turpis, quis malesuada urna tempor eu. Integer sollicitudin scelerisque nisl, vel elementum neque dictum imperdiet. Nam ornare laoreet accumsan. Suspendisse potenti. Nulla ultricies auctor ante ut fringilla. Nam auctor gravida lorem sodales aliquam. Praesent viverra pulvinar odio, nec facilisis sem bibendum vel.', '2010-01-20 10:15:00'),
(2, 'Nulla commodo lectus in nisi posuere congue.', 2, 'Proin pharetra vehicula ipsum, quis interdum est congue vitae. Nullam eleifend, eros et pulvinar scelerisque, mi arcu eleifend urna, sit amet sagittis nisl lectus nec lectus. Vestibulum eu odio sed diam euismod euismod. Nunc adipiscing suscipit rutrum. Quisque sit amet tincidunt felis. Fusce molestie sem sit amet elit semper id accumsan quam commodo. Donec egestas, velit vitae porttitor pulvinar, odio tellus adipiscing dolor, ac euismod sem nulla vitae nibh.', '2010-03-07 10:25:00'),
(3, 'Sed vitae quam orci, et egestas mauris.', 3, 'Nunc faucibus consectetur placerat. Pellentesque consequat, ligula quis tempor dictum, tortor elit eleifend massa, in pulvinar lorem odio eget nunc. Sed tempor consequat lectus ac auctor. Donec fringilla semper augue et ultricies. Curabitur in volutpat massa. Sed vitae elit diam. Nullam nec libero sapien, eu venenatis lacus. Donec ut leo metus, eu pretium arcu. Nunc tempus mattis leo vitae auctor. Morbi ut diam a ante accumsan sodales id nec arcu. Etiam nec tellus arcu. Etiam ut neque id est dapibus viverra nec eget diam. In vulputate ultrices porttitor. Vivamus lobortis lacus ut odio euismod tristique. Integer imperdiet diam ac velit molestie ut commodo tortor feugiat. Sed semper, tortor a sollicitudin adipiscing, nisl nisl congue est, ac consectetur massa lectus facilisis massa.', '2010-03-31 10:35:00'),
(4, 'Ut dignissim lectus nec dolor rutrum ultricies.', 4, 'Quisque ultrices faucibus tempus. Phasellus ut dignissim orci. Fusce suscipit enim quis mauris sodales ac ullamcorper velit interdum. Maecenas iaculis molestie libero in varius. Duis ut purus nibh, ac mattis diam. Phasellus ullamcorper urna non erat aliquet et congue nibh facilisis. Mauris tincidunt urna eu neque consectetur blandit. Nunc volutpat pellentesque mattis. Nam tortor lorem, euismod ac congue ut, sodales ut tortor. Nulla egestas mi quis sem ornare feugiat. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec mattis tortor nibh, vitae pharetra augue. Ut ipsum velit, viverra et porta eget, volutpat eget ipsum.', '2010-05-29 10:45:00'),
(5, 'Proin at tellus leo, ut dapibus augue.', 5, 'Integer sit amet sodales velit. Aliquam eu lorem ipsum. Donec blandit scelerisque semper. Proin pharetra bibendum lacinia. Vivamus consectetur ipsum scelerisque urna elementum ut volutpat nibh faucibus. Nulla euismod imperdiet pellentesque. Nullam velit diam, viverra vitae faucibus et, viverra at eros. Fusce at odio congue est lobortis placerat. Mauris mi leo, dignissim euismod auctor ut, elementum eu arcu.', '2010-07-02 10:15:00'),
(6, 'Aenean sed nunc a lorem ullamcorper porttitor nec ac nisl.', 2, 'Aenean congue suscipit velit sed ullamcorper. Sed dignissim nibh egestas nunc semper egestas. Nullam euismod nisi nec urna convallis non bibendum sem pellentesque. Phasellus ut mi eget felis elementum hendrerit in scelerisque sapien. Praesent in mi leo, nec volutpat nisl. Duis sed porta nulla. Pellentesque a metus feugiat odio pretium feugiat. Pellentesque dictum interdum nisl, ut bibendum diam feugiat eu. Sed sapien lectus, egestas ut fermentum in, laoreet sit amet arcu. Sed semper, mauris sit amet ullamcorper facilisis, risus ligula euismod diam, vel aliquam erat nisl eu sapien. Etiam mattis lacinia magna, at dictum lacus faucibus eget. Suspendisse diam odio, vestibulum et convallis eget, iaculis sit amet magna. Nullam pulvinar tortor vel ante dapibus sagittis. Etiam quam nibh, consequat in euismod ut, vestibulum non odio.', '2010-08-15 10:25:00'),
(7, 'Donec egestas risus vel mi tempus vulputate.', 3, 'Aliquam erat volutpat. Fusce quam nisi, hendrerit non tincidunt vehicula, consequat vel lorem. Vestibulum pharetra pellentesque justo id tincidunt. Donec faucibus venenatis rutrum. Vestibulum commodo, ante quis suscipit pharetra, felis neque ullamcorper quam, nec pretium turpis tortor vel dui. In sit amet mi ligula. Quisque sit amet neque dui, at gravida leo. Nam tincidunt volutpat magna varius tempus. Mauris varius libero sit amet augue tincidunt molestie. Aenean porta ultrices rhoncus. Proin dolor enim, consequat et mollis porta, semper id leo. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis consequat justo id ligula laoreet non vestibulum risus pulvinar. Vestibulum et convallis orci. Maecenas posuere magna malesuada nisi luctus dignissim. Ut nec quam mauris, at scelerisque nibh.', '2010-08-15 10:35:00'),
(8, 'Aenean a tellus placerat turpis laoreet ultricies.', 5, 'Integer lobortis suscipit lectus a pretium. Vivamus vitae iaculis purus. Nam ut nisi libero, at pharetra est. Mauris ut lorem velit, a pharetra enim. Pellentesque rutrum congue bibendum. Fusce eu eros at dui porta semper. Sed nec sem luctus sapien sodales lobortis a non nunc. Aenean ac urna risus. In semper pellentesque nisl nec iaculis. Integer feugiat ante at nulla porta pulvinar. Sed imperdiet molestie lorem. In pellentesque lacus sed ligula ultrices at imperdiet tellus placerat. Praesent aliquam mollis cursus.', '2010-11-17 10:45:00'),
(9, 'Suspendisse malesuada tellus id nulla tincidunt in tincidunt odio rhoncus.', 1, 'In eget dolor sapien, eu pretium arcu. Curabitur sed felis quis nisl interdum molestie sed vel elit. Quisque viverra, mauris ac faucibus facilisis, lacus tellus pellentesque urna, ullamcorper bibendum ante ligula ac eros. Integer placerat dignissim purus in eleifend. In mollis odio posuere augue laoreet pellentesque. Vivamus euismod pharetra turpis, et mattis dui sodales non. Sed fermentum lacus non leo porttitor tempor. Morbi augue nisi, luctus nec pellentesque vitae, adipiscing eget felis. Quisque porttitor metus in erat sodales vulputate. Integer a mauris diam, quis vehicula odio. Fusce quis elit quis mi eleifend cursus eu ut urna. Aliquam erat volutpat. Donec placerat, justo ac tincidunt cursus, arcu magna tristique odio, vel dignissim elit lorem quis velit. Nam eget nisl et elit aliquam pulvinar. Pellentesque vitae augue eget metus consequat feugiat id semper turpis. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.', '2010-12-21 10:15:00'),
(10, 'Vestibulum sed leo ipsum, at fringilla libero.', 5, 'Nulla nec justo ante, ac ultricies purus. Morbi vitae neque massa. Duis quis magna et magna rutrum sollicitudin. Nunc purus enim, vestibulum in tincidunt in, tempor porta elit. Sed ultricies fermentum porttitor. Donec enim lacus, vulputate non porta quis, mollis imperdiet ligula. Curabitur vulputate rhoncus urna at scelerisque. Aenean vitae massa at leo consectetur rutrum nec ac neque. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Praesent vestibulum consectetur purus, vel lacinia lectus placerat sed. Cras ipsum enim, eleifend ut ornare ac, congue sed dolor.', '2011-02-14 10:25:00'),
(11, 'Donec eu arcu nisl, pellentesque tempus velit.', 7, 'Pellentesque gravida, urna nec aliquet gravida, sapien libero malesuada mi, quis rhoncus metus diam bibendum diam. Nam et hendrerit diam. Ut at nisi laoreet justo adipiscing venenatis ac non ligula. Cras cursus est nec urna blandit vehicula tristique libero tincidunt. Aliquam ultricies quam ut eros aliquet ut luctus tellus viverra. Fusce nunc elit, sagittis in eleifend ut, ultricies eu massa. Morbi a odio ante, vel lobortis sapien.', '2011-03-18 10:35:00'),
(12, 'Nam at dui id mi eleifend suscipit.', 9, 'Maecenas non dolor libero. Duis sit amet sapien eget ipsum pulvinar cursus sit amet nec metus. In non nunc sem. Vivamus metus ligula, pretium ut pharetra ut, semper sed magna. Aliquam suscipit vulputate turpis nec condimentum. Nunc dignissim nibh sem. Aliquam turpis nisl, ultrices ac ullamcorper at, hendrerit iaculis magna. Aenean at purus sit amet risus condimentum consectetur. Nullam condimentum condimentum hendrerit. Nulla ut hendrerit eros. Quisque mollis, odio vel ornare viverra, dolor eros mollis eros, eu venenatis tellus lorem nec urna.', '2011-04-22 10:45:00'),
(13, 'Praesent tempor hendrerit urna, sit amet commodo sapien interdum ac.', 10, 'Nulla euismod scelerisque mi, aliquet tincidunt nisi rhoncus ut. Donec varius, nunc in eleifend blandit, erat velit ornare magna, ut vestibulum lacus quam ac magna. Integer ut dolor sapien. Curabitur sed augue est, eu pharetra turpis. Suspendisse ornare hendrerit mattis. Vestibulum quis lobortis tellus. Mauris mattis, urna porttitor convallis tempus, velit massa suscipit nibh, vel consectetur magna mauris ut dui. Nullam eget tristique est. Curabitur sit amet aliquet dui. Curabitur volutpat, nisl eget tincidunt convallis, ligula nunc blandit arcu, cursus pharetra turpis erat a libero. Praesent a molestie libero. Suspendisse potenti. Lorem ipsum dolor sit amet, consectetur adipiscing elit.', '2011-04-23 10:15:00'),
(14, 'Curabitur vitae ipsum velit, nec lacinia nulla.', 5, 'Curabitur justo diam, rutrum euismod congue quis, vulputate id velit. Aliquam sagittis blandit elit, ut eleifend felis hendrerit fermentum. Quisque non ipsum ligula, tempus tincidunt sem. Maecenas id porttitor lorem. Nullam urna purus, tincidunt porta feugiat vel, eleifend eu ipsum. Etiam vel accumsan tellus. Duis ac nisl augue, at dignissim sem. Phasellus imperdiet eleifend facilisis. Pellentesque pretium, sapien in pretium commodo, tortor magna posuere nunc, nec blandit ligula dui sed nibh. Donec sed posuere mauris. Proin commodo ultrices elit, at mollis quam imperdiet quis. Integer vitae felis lorem. Sed in semper turpis. Quisque ac nulla eleifend velit molestie feugiat.', '2011-06-10 10:25:00'),
(15, 'Mauris fermentum est non ipsum facilisis luctus.', 5, 'Donec quis enim molestie arcu aliquam tristique. Cras rhoncus massa id ligula congue vitae vehicula purus tincidunt. Mauris aliquet ante in orci fringilla nec rhoncus lorem pharetra. Vivamus nibh libero, bibendum id bibendum quis, vehicula ac mi. Maecenas semper sollicitudin velit, sed pellentesque nibh interdum non. Pellentesque varius diam neque. Sed mi nulla, tempus sed rhoncus sed, aliquam a dolor. Maecenas eu dui dui. Sed eleifend dolor in massa fringilla mollis aliquam mauris laoreet. Nulla facilisi. Quisque tempor cursus nisl, eget vehicula felis consectetur vel. Proin posuere cursus dui, ac lacinia mi sagittis quis. Praesent ultricies dapibus mattis.', '2011-07-07 10:35:00'),
(16, 'Duis eget diam id nisl convallis posuere sit amet sed odio.', 6, 'Pellentesque dapibus dignissim lectus, aliquam vehicula leo consequat in. Sed ac nisl nibh. Morbi leo ante, tristique a dapibus in, facilisis a odio. Sed ultrices quam eget nisl rutrum tempor. Mauris non metus erat. Vivamus nec ipsum est, eu facilisis lacus. Proin suscipit adipiscing porttitor. Sed quis sem eu enim tempor volutpat eget ac ipsum.', '2011-07-13 10:45:00'),
(17, 'Maecenas ut justo ac quam egestas vehicula ut hendrerit neque.', 7, 'Quisque scelerisque tristique pharetra. Mauris quis diam id libero rhoncus porttitor eu ut nisl. Vivamus at pulvinar nisi. Nulla semper est pretium est viverra tempus blandit tellus semper. Aenean eu sagittis libero. Nulla mollis sapien eu urna aliquet aliquam. Aenean quis est non libero facilisis pretium vel ac nisl. Vivamus luctus aliquet diam, sit amet consequat ligula tincidunt a. Sed viverra tristique mi, nec dignissim libero congue at. Fusce sollicitudin sapien eget nisl aliquet at mattis nisl gravida. Nunc congue, arcu sed posuere malesuada, nibh sapien aliquet tellus, a varius sapien enim sed augue. Quisque et massa sed augue interdum hendrerit. Donec vel eleifend dui. Donec rutrum, nulla at tincidunt suscipit, mi est auctor turpis, ut ultrices nibh augue nec dui.', '2011-08-25 10:15:00'),
(18, 'Nullam feugiat aliquam velit, eu adipiscing diam fermentum ut.', 4, 'Vivamus tempor cursus eros, ut lobortis diam sagittis hendrerit. Fusce at mauris et neque mattis facilisis vel a libero. Sed non justo eget quam ultricies lacinia. Nullam facilisis luctus enim, sit amet molestie arcu scelerisque et. Mauris sed pretium mauris. Vestibulum orci purus, rhoncus at posuere non, iaculis in arcu. Phasellus interdum dolor at dui commodo fringilla. Fusce vitae mauris ut est tempus tempus. Nam ac turpis ut lorem auctor accumsan. Sed gravida vehicula nisi, sollicitudin ultrices eros vulputate sed. Sed tempor ante non elit laoreet luctus. Fusce ut velit risus. Etiam convallis turpis sed erat pellentesque blandit.', '2011-09-05 10:25:00'),
(19, 'Curabitur molestie congue libero, ac tempus diam pharetra ac.', 4, 'Nunc placerat fringilla velit, id commodo mauris euismod at. Cras dignissim nisi vitae urna aliquam sit amet aliquam neque accumsan. Morbi eu dui eu nisl porttitor consectetur. Sed pretium est at velit sodales in tempor felis feugiat. Ut ornare, felis sed gravida tincidunt, velit tortor ultrices magna, et bibendum felis purus nec velit. Fusce fermentum magna at elit facilisis tincidunt. Aenean bibendum turpis ut risus viverra tempor. Sed id lectus magna, vitae tristique est. Donec condimentum tortor sit amet justo placerat accumsan. Etiam eu erat vitae nisl rhoncus tristique. Duis adipiscing rhoncus pulvinar. Pellentesque nulla dui, commodo vehicula consequat non, imperdiet sed velit. Sed ac imperdiet neque. Proin vitae ornare purus. Phasellus ac diam mauris. Duis venenatis faucibus sem, at mattis tellus eleifend non.', '2011-10-11 10:35:00'),
(20, 'Nullam vel sapien felis, nec aliquam lacus.', 2, 'Sed pretium feugiat interdum. Duis fringilla fringilla nibh a tempus. Ut mattis sagittis quam ut tincidunt. Maecenas diam dui, fermentum vel imperdiet suscipit, euismod vitae augue. Integer ultricies dui quis metus dapibus lobortis ut ac ipsum. Maecenas cursus ornare semper. Ut pretium dolor ac metus tempus ornare. Pellentesque a est purus, fringilla molestie elit. Nulla facilisi. Aenean sed leo eu orci imperdiet vehicula sit amet quis nisi. Vestibulum sollicitudin nisl sed risus posuere in sollicitudin risus facilisis. Vivamus at auctor urna. Sed tincidunt, est id pulvinar dictum, neque nibh consectetur libero, id consequat eros orci et felis. Nullam non ligula justo, vitae gravida nulla. Phasellus eget lacus diam. Nullam non tortor eget velit tincidunt tristique.', '2011-11-11 10:45:00'),
(21, 'Etiam lobortis nulla et nibh bibendum luctus.', 1, 'Nunc ligula purus, laoreet in congue vel, dictum vel est. Suspendisse sed tempus nisl. Curabitur cursus lectus eget libero ullamcorper sed feugiat lorem suscipit. In feugiat nulla quis nisl suscipit et ultricies risus viverra. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam diam diam, eleifend at sagittis nec, vulputate ac mi. Nulla non sem in est congue facilisis eu a massa. Vivamus ultricies elit in augue feugiat sollicitudin.', '2011-12-01 10:15:00'),
(22, 'Etiam non velit non ante porta eleifend ut in lacus.', 1, 'Suspendisse potenti. Nam purus purus, sodales sit amet egestas quis, fermentum vitae dolor. Mauris leo dolor, pretium eu sagittis sit amet, aliquet id turpis. Proin et nisl quis urna posuere tincidunt. Cras a dolor magna, et varius risus. Curabitur malesuada mattis diam, sit amet egestas libero consectetur vel. Sed quis tempor dui. Aenean tempus urna id nibh volutpat molestie. Ut tristique ultricies tortor et laoreet.', '2011-12-05 10:25:00'),
(23, 'Quisque sed lacus nulla, vitae lacinia ligula.', 8, 'Aliquam at quam sit amet dolor mollis auctor at in metus. Maecenas scelerisque diam in sapien commodo adipiscing. Nam purus urna, cursus sit amet luctus non, mattis nec odio. Sed sapien dui, pharetra at iaculis sit amet, tincidunt et magna. Proin viverra quam a ante mattis cursus nec et nulla. Quisque odio tortor, eleifend id rutrum vel, feugiat in nisi. Aliquam neque neque, venenatis at lacinia vestibulum, elementum et massa. Nam faucibus, massa vitae dapibus lacinia, nibh lectus iaculis nisl, id pretium libero purus sit amet lectus. Pellentesque mattis aliquet tincidunt. Nam sit amet fermentum sem.', '2011-12-15 10:35:00'),
(24, 'Ut eleifend fermentum lectus, vel placerat velit hendrerit vel.', 8, 'Suspendisse vulputate arcu ac dui imperdiet sodales. In condimentum leo et massa venenatis commodo sed in neque. Maecenas tortor felis, condimentum nec ultricies sed, convallis sit amet odio. Phasellus ultricies, libero sed pharetra cursus, magna metus auctor turpis, eget commodo sapien lorem eget nisl. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi sodales dictum enim, vel viverra massa semper sit amet. Quisque dictum sodales justo. Duis pellentesque dignissim pretium. Cras nec velit ac est tempor adipiscing. Cras vitae malesuada nibh. Vestibulum euismod, erat et laoreet consequat, nisl odio porttitor erat, vitae volutpat libero augue quis sem. Sed ac orci ac quam semper mollis. Maecenas id felis erat, non suscipit libero. Nullam placerat nulla sapien, sit amet aliquet enim. Etiam tincidunt mattis sapien at tincidunt.', '2011-12-25 10:45:00'),
(25, 'Nulla ullamcorper dictum risus, suscipit porttitor nisi facilisis id.', 1, 'Praesent ultrices est id tellus dignissim cursus. Aenean tellus arcu, ullamcorper vitae luctus quis, suscipit sit amet massa. Quisque dictum massa sed justo laoreet commodo. Praesent ut neque neque. Cras in fringilla lorem. Ut quis justo erat. Mauris rutrum arcu vel nisl tincidunt non aliquam quam fringilla. Nam dapibus porta leo, in faucibus ipsum molestie nec.', '2011-12-31 10:15:00'),
(26, 'Cras blandit arcu a nisi aliquam adipiscing.', 2, 'Mauris ut massa lacus, vel vestibulum arcu. Etiam vehicula risus vitae neque luctus lobortis. Aliquam ac lacus mauris. Vivamus dapibus elit sit amet lorem dictum pretium. Nullam tempus placerat lacus, nec cursus magna pellentesque nec. Curabitur sem velit, consectetur eu commodo et, rhoncus quis dolor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Pellentesque libero elit, lobortis non rutrum vel, malesuada ac odio. Sed et nisi sed neque auctor viverra vel eu lorem. Donec at nisl nec purus tempus feugiat eu sed ligula.', '2012-01-05 10:25:00'),
(27, 'Sed eu nulla nunc, sit amet laoreet lacus.', 3, 'Curabitur eu arcu vitae erat lobortis iaculis. Duis iaculis tempor ligula nec volutpat. Nunc tincidunt lectus non elit varius a elementum nulla cursus. Fusce tristique risus eleifend leo scelerisque convallis. Phasellus sed purus placerat dolor interdum dictum. Mauris nunc eros, malesuada sit amet rutrum eu, sagittis nec erat. Ut sed turpis in metus venenatis dignissim. Nulla lacus enim, facilisis eget elementum eget, suscipit sit amet justo.', '2012-01-07 10:35:00'),
(28, 'Sed mattis nisl a ipsum faucibus a commodo massa auctor.', 4, 'Nam sed urna tellus. Proin adipiscing felis sed turpis aliquam et faucibus nunc blandit. Sed mattis, lacus et porta sodales, purus urna mattis urna, sed rhoncus justo augue ac enim. Phasellus non feugiat sapien. Nam quis elit sed nisi auctor viverra id et erat. Pellentesque malesuada, elit nec feugiat ultricies, ligula lorem lobortis lorem, eu sodales magna elit in enim. Nulla pulvinar nisi ac leo mollis eu iaculis massa sollicitudin.', '2012-01-08 10:45:00'),
(29, 'Proin ullamcorper tincidunt lacus, at venenatis dolor elementum ut.', 5, 'In in dui ut eros laoreet vestibulum eu quis mauris. Nunc sed faucibus orci. Proin magna velit, tincidunt lobortis ultrices tempor, eleifend non nibh. Nam eleifend, erat sit amet ultrices ornare, erat enim commodo massa, vitae pellentesque lectus diam eu lectus. In consectetur, enim et vestibulum viverra, turpis urna accumsan enim, eleifend ullamcorper dui eros sed tortor. Pellentesque magna velit, vulputate quis vulputate sit amet, porttitor et erat. Donec sed urna lorem. Quisque sed nisi metus. Integer rutrum sapien ac lorem varius convallis. Aliquam diam velit, volutpat nec auctor et, sodales eu quam. Pellentesque sollicitudin convallis volutpat. Donec nec consequat tellus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.', '2012-01-11 10:15:00'),
(30, 'Vivamus quis ante eget nulla consequat vulputate.', 2, 'Aenean tristique, mauris non blandit pretium, justo est posuere nisl, eu accumsan elit lorem ac lacus. Maecenas fermentum turpis sed orci placerat interdum. Ut eget orci vitae sem dapibus pretium. Nulla sit amet neque non lectus viverra suscipit ut et magna. Morbi a quam enim. Mauris vitae ultrices metus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; In ornare velit id dolor ultricies ut pretium est ornare. Sed eget ipsum a leo faucibus scelerisque. Nulla id massa quis lacus lobortis volutpat eget eu ipsum. Nam porta vestibulum magna.', '2012-01-15 10:25:00'),
(31, 'Nulla pulvinar dui vitae lacus ornare condimentum.', 3, 'Vestibulum pharetra ultricies est, a sodales arcu porttitor a. Nulla quis lacus elit. Duis eget metus a leo interdum porta et a turpis. Nunc gravida, felis vitae cursus pharetra, enim enim rutrum quam, vel molestie tortor erat ac magna. Proin eget nibh non leo dapibus gravida. Integer porttitor augue in felis imperdiet id commodo urna fringilla. Praesent congue pharetra ligula. Proin massa est, imperdiet sed gravida et, pulvinar vel enim. Vivamus ac nunc nec sem tempus gravida.', '2012-01-18 10:35:00'),
(32, 'Donec vel nisl vel nibh sollicitudin aliquam in vel lorem.', 5, 'In hac habitasse platea dictumst. Nam neque ligula, pulvinar id malesuada et, pulvinar vel lectus. Integer ut lectus velit. Nam dictum purus vitae ligula gravida vitae molestie leo tempor. Pellentesque venenatis enim in felis suscipit at pharetra quam auctor. Fusce luctus tincidunt ultricies. Nunc dapibus, dolor vitae venenatis pharetra, orci orci tristique elit, eu interdum nisi quam et risus. Cras eu ligula eu neque adipiscing dictum. Vivamus sed ligula nibh. Quisque mattis, sapien vel porta viverra, lorem metus vestibulum risus, a ultricies sem urna id tortor. Pellentesque sollicitudin, sem sed lacinia malesuada, ante ligula pharetra sapien, non vulputate justo nulla et tellus.', '2012-01-21 10:45:00'),
(33, 'Etiam vulputate nisl vel tortor molestie volutpat.', 1, 'Cras vulputate ultrices ultricies. Donec porta, velit in luctus consequat, tortor lorem commodo diam, dignissim venenatis metus odio id tellus. Donec risus sapien, consequat non pharetra a, hendrerit id elit. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam at tortor orci. Ut porta metus a eros scelerisque varius. Sed ultricies, dolor eget gravida vulputate, ligula sem porttitor felis, eget commodo mauris urna vel dui. Proin dignissim, elit a tristique condimentum, velit diam ullamcorper urna, vehicula malesuada lacus lorem at risus. Donec eu sem massa. Nullam justo lorem, malesuada a blandit scelerisque, faucibus eget massa. Sed ac tempor velit.', '2012-01-22 10:15:00'),
(34, 'Mauris ut lectus a velit venenatis accumsan nec vitae eros.', 5, 'Cras malesuada nunc eu mauris lobortis vestibulum. Curabitur odio urna, tincidunt quis convallis ut, accumsan a odio. Proin pretium accumsan ante, nec congue enim dapibus vel. Nam interdum lacinia tortor, ullamcorper luctus orci sagittis id. Curabitur vehicula, mi sit amet tincidunt tempus, velit neque tincidunt velit, quis pulvinar odio nibh a nulla. Nulla non quam sit amet augue elementum mattis ac vel massa. Nullam vehicula convallis ullamcorper. Sed convallis pretium rhoncus. Nullam vitae ante sit amet arcu volutpat malesuada sed at metus. In hac habitasse platea dictumst. Vestibulum gravida sollicitudin justo, nec dignissim lorem tincidunt a. Maecenas sed diam id dui tincidunt facilisis. Cras laoreet tellus augue, sed lobortis ligula. In tincidunt dignissim adipiscing. Cras eget lacus mi.', '2012-01-25 10:25:00'),
(35, 'Etiam at orci libero, non tempor lectus.', 7, 'Morbi justo velit, tempor quis convallis non, vestibulum nec turpis. Phasellus vel lectus nisl. Nullam non mi ac nibh commodo varius a et lorem. Proin sapien est, sagittis ac varius in, auctor at justo. Praesent venenatis fringilla odio at fringilla. Maecenas vitae orci velit, in fringilla diam. Sed auctor odio eget sapien cursus sed cursus urna scelerisque. Suspendisse at magna diam, eget semper purus. Morbi a nisl ipsum, in gravida enim. Integer scelerisque nunc ac tellus porta at placerat purus aliquet.', '2012-01-26 10:35:00'),
(36, 'Aliquam sit amet leo a orci vehicula luctus id ac augue.', 9, 'Suspendisse nulla risus, egestas sed fermentum et, molestie eu diam. Vivamus sem tellus, pulvinar non pretium sed, condimentum id quam. Etiam faucibus interdum augue, vitae volutpat ante porttitor a. Curabitur cursus felis consectetur erat mattis tincidunt. Duis pulvinar, nulla non lacinia dapibus, dui neque rutrum ante, sit amet venenatis nunc diam ornare turpis. Fusce dictum mauris quis tortor vulputate sollicitudin. In neque quam, lobortis in venenatis non, auctor ut magna. Nullam non augue diam, eu aliquam lectus. Aliquam laoreet risus adipiscing sem facilisis eget consequat dui venenatis. Donec vitae sapien orci, nec accumsan nulla. Phasellus ligula quam, volutpat vel elementum non, pellentesque a libero. Vivamus id urna et metus ullamcorper convallis. Fusce sit amet eros et elit auctor gravida vel id ante.', '2012-01-27 10:45:00'),
(37, 'Morbi ac nisl sed nulla condimentum mattis.', 10, 'Proin auctor nisi vitae augue tristique cursus. Quisque at nibh nec est suscipit pulvinar in feugiat massa. Sed nec lectus orci, quis pulvinar diam. Sed consequat sem tempus risus ultricies et feugiat sapien convallis. In hac habitasse platea dictumst. Nam porta pulvinar arcu non consequat. Nulla eget risus metus, at fermentum ligula. Phasellus sed tincidunt odio. Quisque leo augue, imperdiet ornare faucibus ac, fringilla a orci. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vivamus metus tortor, cursus ut elementum id, luctus eu dolor. Phasellus imperdiet erat in libero accumsan viverra. Aliquam mollis ante nibh.', '2012-01-31 10:15:00'),
(38, 'Morbi et quam eu purus sodales rutrum vel at dui.', 5, 'Sed mattis porta ligula, ac convallis purus adipiscing at. Nullam nisl justo, viverra et consectetur ac, facilisis eget nisi. Nulla facilisi. Pellentesque id iaculis nibh. Donec elementum facilisis sapien in congue. Nunc tincidunt lorem nec turpis euismod at sagittis magna fermentum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce ac sapien vitae nisi molestie tempor. Curabitur molestie vehicula venenatis. Curabitur sit amet dui at augue vulputate volutpat id sit amet est. Aenean vitae mi sodales nulla venenatis rhoncus. Donec dignissim arcu nec ligula vulputate vitae sodales tortor condimentum. Vestibulum nec lectus quis risus imperdiet facilisis. Duis nisl ipsum, sagittis sed condimentum et, sodales eget leo.', '2012-02-01 10:25:00'),
(39, 'Integer porttitor ipsum et dui congue ac scelerisque libero tincidunt.', 5, 'Pellentesque nulla tortor, interdum at cursus id, consectetur vitae est. Morbi ullamcorper congue rhoncus. Aliquam ultricies ante sit amet quam pulvinar at scelerisque diam auctor. Quisque ac urna sed libero sollicitudin dignissim. Etiam a gravida libero. Morbi at orci in nulla sodales consequat. Sed in nisi mauris, ac bibendum libero. Suspendisse ultrices, enim non sagittis convallis, libero velit ornare diam, et porttitor tortor eros vitae nunc. Fusce malesuada orci id felis rhoncus hendrerit. Nunc nec luctus magna.', '2012-02-03 10:35:00'),
(40, 'Aliquam ullamcorper consequat leo, eget aliquam mi hendrerit a.', 6, 'Curabitur id vestibulum arcu. Nam adipiscing leo gravida neque molestie tincidunt. Nam in varius sapien. Mauris vestibulum, mi sed dignissim luctus, orci tellus luctus orci, vitae semper mi odio eget risus. Aenean vitae nibh id nisl porta adipiscing ut quis nisi. Vivamus augue arcu, ullamcorper vel dapibus vel, cursus eu lectus. Pellentesque dapibus lorem sed mauris pharetra non pharetra turpis sodales. Etiam nisi erat, suscipit id luctus sed, tempor id orci. Praesent placerat placerat pharetra. Aliquam at sem eu eros ullamcorper vulputate.', '2012-02-03 10:45:00'),
(41, 'Aliquam sed metus urna, in feugiat nisi.', 7, 'Maecenas non nunc ut mi porta lacinia id ac ante. In sodales malesuada velit faucibus posuere. In in ligula diam. Aliquam erat volutpat. Etiam dapibus eleifend odio sit amet lacinia. Sed at odio vel risus ultrices faucibus. Proin rhoncus, nisi sed suscipit tempor, risus augue tristique ipsum, quis tincidunt mauris ipsum et dolor. Donec commodo dictum ligula et vestibulum. Proin et arcu elit. Morbi tempus mi sed magna tincidunt ut lobortis nisl venenatis. Morbi iaculis dignissim lacinia. Nam ornare euismod libero id dignissim.', '2012-02-04 10:15:00'),
(42, 'Curabitur a arcu vel lectus tincidunt faucibus.', 4, 'Vivamus tincidunt eros ac libero adipiscing consectetur. Cras ultricies dictum dui eu dictum. Sed feugiat nunc non enim consequat suscipit. Mauris ac justo quis nulla posuere commodo. Praesent ornare lorem sit amet purus hendrerit quis porta enim pharetra. Sed eu justo nibh, ac tristique neque. Duis pharetra, est eget tristique hendrerit, mi justo bibendum dui, in mattis massa nulla eget arcu. Aliquam augue eros, hendrerit quis mollis sed, congue eu urna. Suspendisse potenti. In facilisis augue a ante commodo non tristique nunc rutrum. Sed pharetra ultrices felis, in posuere velit pulvinar vitae. Vivamus lectus justo, interdum congue vulputate nec, eleifend et tortor. Ut nec odio nec nibh volutpat convallis. In in lectus ligula, id luctus arcu. Donec ultricies, metus nec dictum sollicitudin, arcu massa viverra dolor, in interdum nibh dui sit amet leo. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;', '2012-02-05 10:25:00'),
(43, 'Fusce faucibus dolor quis arcu gravida eu tristique nibh fringilla.', 4, 'Pellentesque nisi justo, lacinia vel blandit luctus, tristique lobortis lorem. Mauris vestibulum, arcu ac ornare suscipit, justo elit mattis ipsum, et ornare velit sem et libero. Integer eget elit non lacus scelerisque consectetur. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus non eros sem, sed luctus ligula. Donec et velit ac lorem accumsan malesuada ac nec ipsum. Nulla pulvinar dui eget felis blandit aliquet vel sit amet justo. Aliquam ac viverra nulla. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '2012-02-08 10:35:00'),
(44, 'Nulla feugiat varius sapien, eu vestibulum urna consequat in.', 2, 'Praesent blandit fermentum ante ut adipiscing. Maecenas commodo fringilla dignissim. Sed quam diam, elementum a egestas eget, lobortis et massa. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Integer felis erat, cursus eu tempor sit amet, convallis gravida urna. Sed eu est id libero lacinia laoreet non eu magna. Morbi non sapien id augue dignissim interdum. In a sollicitudin dolor. Maecenas condimentum lobortis sapien, mollis iaculis tortor vulputate sit amet. Ut elementum lorem dui. Duis aliquam risus non nunc sagittis eget volutpat leo sagittis. Ut vel leo purus, at luctus ligula. Proin eu neque in augue luctus interdum vitae quis nunc. Sed nulla dolor, consectetur vitae dignissim a, lacinia non nisi. Suspendisse vehicula erat sit amet tellus pharetra lobortis. Nunc magna orci, fermentum sit amet ullamcorper a, interdum non libero.', '2012-02-09 10:45:00'),
(45, 'Phasellus fermentum purus risus, at rhoncus nulla.', 1, 'Aliquam erat sapien, auctor placerat adipiscing nec, tincidunt semper est. Maecenas nulla lacus, laoreet nec convallis sit amet, condimentum sed erat. Suspendisse ac enim ut nisi elementum molestie in in dolor. Pellentesque fringilla, libero vitae vehicula luctus, risus ipsum ullamcorper ligula, at consequat odio purus non diam. Vivamus mattis urna sed leo ullamcorper at mattis odio interdum. Praesent sem dui, porta at vestibulum in, sollicitudin pharetra lorem. Quisque eu sapien felis, sed congue diam.', '2012-02-10 10:15:00'),
(46, 'Donec congue vulputate risus, in luctus nisl sagittis vitae.', 1, 'Nunc tempus justo vel quam rutrum pulvinar ac eget nulla. Phasellus non turpis eleifend purus vestibulum posuere. Donec tincidunt consectetur massa, quis aliquet purus tristique sit amet. Curabitur eget viverra nisi. Cras sit amet sem a sapien bibendum iaculis id ac turpis. Phasellus in velit nulla. Quisque dolor nisi, mollis quis pulvinar sed, vestibulum sit amet leo. Proin vitae magna nisi, vel tincidunt massa. Nulla vitae feugiat arcu. Praesent hendrerit ante ac turpis tincidunt in dictum magna commodo. Duis fringilla metus ut tellus dapibus ac dapibus augue iaculis. Vivamus a nulla ac enim convallis sagittis. Nullam ac tortor augue. Sed congue pulvinar elementum.', '2012-02-14 10:25:00'),
(47, 'Nullam egestas ante sed sem ornare commodo.', 8, 'Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nulla rutrum nisi vitae leo mollis iaculis. Phasellus sit amet eros sed turpis auctor ornare. Duis et erat augue, vel luctus eros. Praesent a urna consectetur mauris porta volutpat. Fusce non convallis sapien. Vestibulum dapibus consectetur mi, at pretium massa lacinia vitae. Maecenas mauris nulla, suscipit pellentesque scelerisque laoreet, posuere luctus lacus.', '2012-02-15 10:35:00'),
(48, 'Etiam accumsan urna sit amet tellus ornare et fringilla urna faucibus.', 8, 'Phasellus euismod nisi vitae eros sodales at euismod lectus mattis. Ut venenatis ligula at turpis egestas eu rutrum tellus accumsan. Mauris id enim sem. Duis euismod, magna nec adipiscing imperdiet, massa libero semper nibh, eget egestas augue justo vitae erat. Cras vitae magna volutpat sapien commodo imperdiet. In a nunc ipsum, nec vulputate urna. Fusce semper vehicula aliquam.', '2012-02-16 10:45:00'),
(49, 'Sed quis nunc nisi, at interdum libero.', 3, 'Vestibulum a nisi mi. Fusce lorem ante, rutrum a sagittis sit amet, vehicula ac enim. Morbi ac diam vel dui convallis interdum. Phasellus iaculis varius fermentum. Proin accumsan elementum enim eget pulvinar. Pellentesque tempor congue nunc ac adipiscing. Etiam justo diam, vulputate eget molestie sed, congue vel lacus.', '2012-02-17 10:15:00'),
(50, 'Fusce ut diam hendrerit ante euismod adipiscing.', 2, 'Sed non sapien at lacus feugiat varius sit amet non elit. Aliquam vitae orci ut felis condimentum sodales ut quis sapien. Vestibulum fringilla elit ut dui scelerisque tempor. Nam elementum orci id est sagittis blandit. Donec tempus congue libero eu egestas. Vivamus a cursus nisi. Cras sit amet lobortis urna.', '2012-02-17 16:45:00');

-- --------------------------------------------------------

--
-- Table structure for table `tbl_author`
--

CREATE TABLE IF NOT EXISTS `tbl_author` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `full_name` varchar(128) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=10 ;

--
-- Dumping data for table `tbl_author`
--

INSERT INTO `tbl_author` (`id`, `full_name`) VALUES
(1, 'Lorem Ipsum'),
(2, 'Dolor Sit'),
(3, 'Amet Consectetur'),
(4, 'Adipiscing Elit'),
(5, 'Maecenas Ipsum'),
(6, 'Lacus Bibendum'),
(7, 'Pulvinar Non'),
(8, 'Venenatis Vel'),
(9, 'Mauris Neque');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
